version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springapp:
    build: ./springapp
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/app_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  reactapp:
    build: ./reactapp
    container_name: reactapp
    ports:
      - "3000:80"
    depends_on:
      - springapp

volumes:
  mysql-data:
